spring:
  config:
    use-legacy-processing: true
  profiles:
    active: development
  datasource:
    url: jdbc:mysql://mysql:3306/bluememories?characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties.useUnicode: true
      data-source-properties.characterEncoding: UTF-8
  jpa:
    database: bluememories
    database-platform: org.hibernate.dialect.MySQL8Dialect
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: .
      trigger-file: reload.txt